const data = [
   {
     first_name: 'John',
     last_name: 'Doe',
     email: 'john.doe@example.com',
     skill: 'JavaScript',
     language: 'English',
   },
   {
     first_name: 'Jane',
     last_name: 'Smith',
     email: 'jane.smith@example.com',
     skill: 'React',
     language: 'Spanish',
   },
   {
     first_name: 'Michael',
     last_name: 'Johnson',
     email: 'michael.johnson@example.com',
     skill: 'Python',
     language: 'French',
   },
   {
     first_name: 'Emily',
     last_name: 'Davis',
     email: 'emily.davis@example.com',
     skill: 'Angular',
     language: 'German',
   },
   {
     first_name: 'David',
     last_name: 'Brown',
     email: 'david.brown@example.com',
     skill: 'Node.js',
     language: 'English',
   },
   {
     first_name: 'Sophia',
     last_name: 'Miller',
     email: 'sophia.miller@example.com',
     skill: 'Vue.js',
     language: 'Spanish',
   },
   {
     first_name: 'James',
     last_name: 'Wilson',
     email: 'james.wilson@example.com',
     skill: 'Ruby on Rails',
     language: 'Japanese',
   },
   {
     first_name: 'Olivia',
     last_name: 'Martinez',
     email: 'olivia.martinez@example.com',
     skill: 'PHP',
     language: 'Portuguese',
   },
   {
     first_name: 'Liam',
     last_name: 'Garcia',
     email: 'liam.garcia@example.com',
     skill: 'C++',
     language: 'Mandarin',
   },
   {
     first_name: 'Isabella',
     last_name: 'Lopez',
     email: 'isabella.lopez@example.com',
     skill: 'Java',
     language: 'Italian',
   },
   {
     first_name: 'Noah',
     last_name: 'Gonzalez',
     email: 'noah.gonzalez@example.com',
     skill: 'Kotlin',
     language: 'Russian',
   },
   {
     first_name: 'Mia',
     last_name: 'Hernandez',
     email: 'mia.hernandez@example.com',
     skill: 'Swift',
     language: 'Arabic',
   },
   {
     first_name: 'Lucas',
     last_name: 'Thomas',
     email: 'lucas.thomas@example.com',
     skill: 'Django',
     language: 'Hindi',
   },
   {
     first_name: 'Charlotte',
     last_name: 'Moore',
     email: 'charlotte.moore@example.com',
     skill: 'Laravel',
     language: 'Chinese',
   },
   {
     first_name: 'Ethan',
     last_name: 'Jackson',
     email: 'ethan.jackson@example.com',
     skill: 'Go',
     language: 'Korean',
   },
   {
     first_name: 'Harper',
     last_name: 'Lee',
     email: 'harper.lee@example.com',
     skill: 'JavaScript',
     language: 'English',
   },
   {
     first_name: 'Ava',
     last_name: 'Harris',
     email: 'ava.harris@example.com',
     skill: 'React',
     language: 'Spanish',
   },
   {
     first_name: 'William',
     last_name: 'Clark',
     email: 'william.clark@example.com',
     skill: 'Python',
     language: 'French',
   },
   {
     first_name: 'Ella',
     last_name: 'Young',
     email: 'ella.young@example.com',
     skill: 'Angular',
     language: 'German',
   },
   {
     first_name: 'Alexander',
     last_name: 'Hill',
     email: 'alexander.hill@example.com',
     skill: 'Node.js',
     language: 'English',
   },
   {
     first_name: 'Amelia',
     last_name: 'Green',
     email: 'amelia.green@example.com',
     skill: 'Vue.js',
     language: 'Spanish',
   },
   {
     first_name: 'Daniel',
     last_name: 'Adams',
     email: 'daniel.adams@example.com',
     skill: 'Ruby on Rails',
     language: 'Japanese',
   },
   {
     first_name: 'Abigail',
     last_name: 'Baker',
     email: 'abigail.baker@example.com',
     skill: 'PHP',
     language: 'Portuguese',
   },
   {
     first_name: 'Henry',
     last_name: 'Nelson',
     email: 'henry.nelson@example.com',
     skill: 'C++',
     language: 'Mandarin',
   },
   {
     first_name: 'Sofia',
     last_name: 'Carter',
     email: 'sofia.carter@example.com',
     skill: 'Java',
     language: 'Italian',
   },
   {
     first_name: 'Oliver',
     last_name: 'Mitchell',
     email: 'oliver.mitchell@example.com',
     skill: 'Kotlin',
     language: 'Russian',
   },
   {
     first_name: 'Mila',
     last_name: 'Perez',
     email: 'mila.perez@example.com',
     skill: 'Swift',
     language: 'Arabic',
   },
   {
     first_name: 'Benjamin',
     last_name: 'Roberts',
     email: 'benjamin.roberts@example.com',
     skill: 'Django',
     language: 'Hindi',
   },
   {
     first_name: 'Emma',
     last_name: 'Turner',
     email: 'emma.turner@example.com',
     skill: 'Laravel',
     language: 'Chinese',
   },
   {
     first_name: 'Jacob',
     last_name: 'Phillips',
     email: 'jacob.phillips@example.com',
     skill: 'Go',
     language: 'Korean',
   },
   {
     first_name: 'Emily',
     last_name: 'Parker',
     email: 'emily.parker@example.com',
     skill: 'JavaScript',
     language: 'English',
   },
   {
     first_name: 'Michael',
     last_name: 'Evans',
     email: 'michael.evans@example.com',
     skill: 'React',
     language: 'Spanish',
   },
   {
     first_name: 'Elizabeth',
     last_name: 'Edwards',
     email: 'elizabeth.edwards@example.com',
     skill: 'Python',
     language: 'French',
   },
   {
     first_name: 'Matthew',
     last_name: 'Collins',
     email: 'matthew.collins@example.com',
     skill: 'Angular',
     language: 'German',
   },
   {
     first_name: 'Scarlett',
     last_name: 'Stewart',
     email: 'scarlett.stewart@example.com',
     skill: 'Node.js',
     language: 'English',
   },
   {
     first_name: 'Jack',
     last_name: 'Sanchez',
     email: 'jack.sanchez@example.com',
     skill: 'Vue.js',
     language: 'Spanish',
   },
   {
     first_name: 'Maya',
     last_name: 'Morris',
     email: 'maya.morris@example.com',
     skill: 'Ruby on Rails',
     language: 'Japanese',
   },
   {
     first_name: 'Sebastian',
     last_name: 'Reed',
     email: 'sebastian.reed@example.com',
     skill: 'PHP',
     language: 'Portuguese',
   },
   {
     first_name: 'Grace',
     last_name: 'Rogers',
     email: 'grace.rogers@example.com',
     skill: 'C++',
     language: 'Mandarin',
   },
   {
     first_name: 'Aiden',
     last_name: 'Cook',
     email: 'aiden.cook@example.com',
     skill: 'Java',
     language: 'Italian',
   },
   {
     first_name: 'Zoe',
     last_name: 'Morgan',
     email: 'zoe.morgan@example.com',
     skill: 'Kotlin',
     language: 'Russian',
   },
   {
     first_name: 'Lucas',
     last_name: 'Bailey',
     email: 'lucas.bailey@example.com',
     skill: 'Swift',
     language: 'Arabic',
   },
   {
     first_name: 'Ella',
     last_name: 'Rivera',
     email: 'ella.rivera@example.com',
     skill: 'Django',
     language: 'Hindi',
   },
   {
     first_name: 'Jackson',
     last_name: 'Cooper',
     email: 'jackson.cooper@example.com',
     skill: 'Laravel',
     language: 'Chinese',
   },
   {
     first_name: 'Aria',
     last_name: 'Richardson',
     email: 'aria.richardson@example.com',
     skill: 'Go',
     language: 'Korean',
   },
   {
     first_name: 'Lily',
     last_name: 'Cox',
     email: 'lily.cox@example.com',
     skill: 'JavaScript',
     language: 'English',
   },
   {
     first_name: 'Alexander',
     last_name: 'Ward',
     email: 'alexander.ward@example.com',
     skill: 'React',
     language: 'Spanish',
   }];

   export default data ;
  
 